import Decimal from "break_infinity.js";
import type {
  UnitDefinition,
  UpgradeDefinition,
  CityDefinition,
  KnowledgeSource,
} from "./types";

const d = (value: number) => new Decimal(value);
export const regions = [
  { id: "ancient", name: "Ancient Empires", startIndex: 0 },
  { id: "slavic", name: "Slavic", startIndex: 6 },
] as const;
export const VERSION = "0.0.1";
export const rules = {
  initialEssence: 1,
  baseEssence: 0,
  baseKnowledge: 0,
  costGrowth: 1.045,
  dominionBonus: 0.05,
  conquestReward: 10,
  autosaveSeconds: 30,
};
export const cultRules = {
  followerInterval: 30,
  followersPerFanatic: 1,
  promotionEssence: 100,
  promotionKnowledge: 10,
  speedPerFanatic: 0.1,
  fanaticsPerCircle: 5,
  fanaticUnlockUnit: "lesser_demon",
  promotionCostGrowth: 1.55,
};
export const knowledgeSources: KnowledgeSource[] = [
  {
    id: "scattered",
    title: "Scattered Pages",
    description: "Snatched from the wind, you glimpse eternity.",
    requirement: 0,
    value: 0.16,
  },
  {
    id: "commons",
    title: "The Commoners' Library",
    description:
      "Spoon-fed, pre-chewed pieces of information while you hunger for venison.",
    requirement: 20,
    value: 0.52,
  },
  {
    id: "lord",
    title: "The Lord's Library",
    description:
      "You slip beneath the sheet of night to uncover secrets never meant for peasants.",
    requirement: 60,
    value: 1,
  },
  {
    id: "holy",
    title: "Holy Scripts",
    description: "Sacred words reveal truths hidden behind the altar.",
    requirement: 120,
    value: 2.3,
  },
  {
    id: "forbidden",
    title: "Forbidden Runes",
    description:
      "Even the wisest would burn out their eyes after a single glance.",
    requirement: 450,
    value: 3.8,
  },
  {
    id: "stars",
    title: "Truth Behind the Stars",
    description:
      "You peek beyond the veil of stars and absorb knowledge mortals would never dare to dream of.",
    requirement: 1400,
    value: 6.2,
  },
  {
    id: "abyss",
    title: "Archive of the Abyss",
    description: "Each name reveals a thousand more.",
    requirement: 6000,
    value: 12,
  },
  {
    id: "eternity",
    title: "The Unwritten Codex",
    description: "Study the laws that bind eternity.",
    requirement: 22000,
    value: 24,
  },
];
export const units: UnitDefinition[] = [
  {
    id: "spirit",
    name: "Lesser Spirit",
    tier: 1,
    description: "A whisper made obedient. Gathers the remnants of essence.",
    baseCost: d(10),
    summonTime: 2.4,
    power: d(1),
    essencePerSecond: d(0.5),
    unlockKnowledge: d(0),
  },
  {
    id: "imp",
    name: "Imp",
    tier: 2,
    description: "A restless servant, eager to decipher forbidden texts.",
    baseCost: d(75),
    summonTime: 5,
    power: d(5),
    essencePerSecond: d(2),
    unlockKnowledge: d(10),
  },
  {
    id: "familiar",
    name: "Familiar",
    tier: 3,
    description: "An unseen companion. Feeds the circle with stolen breath.",
    baseCost: d(350),
    summonTime: 9,
    power: d(25),
    essencePerSecond: d(7),
    unlockKnowledge: d(35),
  },
  {
    id: "lesser_demon",
    name: "Lesser Demon",
    tier: 4,
    description: "The first soldier of a war that has not yet begun.",
    baseCost: d(1500),
    summonTime: 24,
    power: d(150),
    essencePerSecond: d(20),
    unlockKnowledge: d(300),
  },
  {
    id: "demon",
    name: "Demon",
    tier: 5,
    description: "An ancient will bound beneath the seal of your name.",
    baseCost: d(8000),
    summonTime: 42,
    power: d(1000),
    essencePerSecond: d(60),
    unlockKnowledge: d(1800),
  },
  {
    id: "greater_demon",
    name: "Greater Demon",
    tier: 6,
    description: "Even the manuscript trembles at its arrival.",
    baseCost: d(40000),
    summonTime: 72,
    power: d(8000),
    essencePerSecond: d(150),
    unlockKnowledge: d(6000),
  },
  {
    id: "bludicka",
    name: "Will-o'-the-wisp",
    region: "slavic",
    tier: 7,
    baseCost: d(250000),
    summonTime: 80,
    power: d(30000),
    essencePerSecond: d(900),
    unlockKnowledge: d(1200),
    knowledgePerSecond: 0.4,
    description: "A wandering light leads lost souls into your circle.",
  },
  {
    id: "rusalka",
    name: "Water nymph",
    region: "slavic",
    tier: 8,
    baseCost: d(1000000),
    summonTime: 95,
    power: d(120000),
    essencePerSecond: d(3000),
    unlockKnowledge: d(4000),
    knowledgePerSecond: 1.5,
    description: "Her river-song draws the living beneath the water.",
  },
  {
    id: "upir",
    name: "Vampire",
    region: "slavic",
    tier: 9,
    baseCost: d(4000000),
    summonTime: 115,
    power: d(500000),
    essencePerSecond: d(10000),
    unlockKnowledge: d(12000),
    knowledgePerSecond: 0,
    description: "An undying hunger turns stolen blood into an army.",
  },
  {
    id: "striga",
    name: "Striga",
    region: "slavic",
    tier: 10,
    baseCost: d(16000000),
    summonTime: 140,
    power: d(2000000),
    essencePerSecond: d(30000),
    unlockKnowledge: d(30000),
    knowledgePerSecond: 4,
    description: "A whispered curse binds the village to your will.",
  },
  {
    id: "lesij",
    name: "Leshij",
    region: "slavic",
    tier: 11,
    baseCost: d(60000000),
    summonTime: 170,
    power: d(8000000),
    essencePerSecond: d(90000),
    unlockKnowledge: d(75000),
    knowledgePerSecond: 8,
    description: "The forest rises at the command of its hidden keeper.",
  },
  {
    id: "cert",
    name: "Chort",
    region: "slavic",
    tier: 12,
    baseCost: d(250000000),
    summonTime: 210,
    power: d(35000000),
    essencePerSecond: d(250000),
    unlockKnowledge: d(180000),
    knowledgePerSecond: 0,
    description: "A horned collector arrives to claim every broken oath.",
  },
];
export const upgrades: UpgradeDefinition[] = [
  {
    id: "charm",
    name: "Charm",
    category: "Follower Gain",
    description: "Follower arrival speed +25%.",
    cost: d(450),
    knowledge: 80,
    kind: "follower",
    factor: 1.25,
  },
  {
    id: "persuasion",
    name: "Persuasion",
    category: "Follower Gain",
    description: "Follower arrival speed +40%.",
    cost: d(1400),
    knowledge: 180,
    requires: "charm",
    kind: "follower",
    factor: 1.4,
  },
  {
    id: "pressure",
    name: "Pressure",
    category: "Follower Gain",
    description: "Follower arrival speed +60%.",
    cost: d(4500),
    knowledge: 360,
    requires: "persuasion",
    kind: "follower",
    factor: 1.6,
  },
  {
    id: "mind_control",
    name: "Mind-control",
    category: "Follower Gain",
    description: "Follower arrival speed +100%.",
    cost: d(14000),
    knowledge: 1800,
    requires: "pressure",
    kind: "follower",
    factor: 2,
  },
  {
    id: "circle",
    name: "Fanatic Training",
    category: "Automation",
    description:
      "Each level teaches Fanatics to summon the next entity. Requires at least one Fanatic; manual summoning is unchanged.",
    cost: d(180),
    knowledge: 18,
    kind: "automation",
    factor: 1,
    repeatable: true,
  },
  {
    id: "pentagram",
    name: "Five-point Seal",
    category: "Pentagram",
    description: "Summoning speed +15%.",
    cost: d(120),
    knowledge: 8,
    kind: "speed",
    factor: 1.15,
  },
  {
    id: "pentagram2",
    name: "Greater Pentagram",
    category: "Pentagram",
    description: "Summoning speed +25% more.",
    cost: d(1800),
    knowledge: 160,
    requires: "pentagram",
    kind: "speed",
    factor: 1.25,
  },
  {
    id: "geometry",
    name: "Sacred Proportions",
    category: "Sacred Geometry",
    description: "All summon costs −15%.",
    cost: d(220),
    knowledge: 15,
    kind: "cost",
    factor: 0.85,
  },
  {
    id: "geometry2",
    name: "Seal of Dominion",
    category: "Sacred Geometry",
    description: "All army power +25%.",
    cost: d(2200),
    knowledge: 110,
    requires: "geometry",
    kind: "power",
    factor: 1.25,
  },
  {
    id: "candles",
    name: "Black Candles",
    category: "Candles",
    description: "Essence generation +25%.",
    cost: d(160),
    knowledge: 12,
    kind: "essence",
    factor: 1.25,
  },
  {
    id: "candles2",
    name: "Ever-burning Wicks",
    category: "Candles",
    description: "Essence generation +40% more.",
    cost: d(1200),
    knowledge: 75,
    requires: "candles",
    kind: "essence",
    factor: 1.4,
  },
  {
    id: "incense",
    name: "Frankincense",
    category: "Incense",
    description: "Knowledge generation +50%.",
    cost: d(350),
    knowledge: 25,
    kind: "knowledge",
    factor: 1.5,
  },
  {
    id: "incense2",
    name: "Myrrh of the Pit",
    category: "Incense",
    description: "Power of tier IV–VI demons +30%.",
    cost: d(3500),
    knowledge: 150,
    requires: "incense",
    kind: "demonPower",
    factor: 1.3,
  },
  {
    id: "charm5",
    name: "Voice of the Legion",
    category: "Follower Gain",
    cost: d(65000),
    knowledge: 8500,
    requires: "mind_control",
    kind: "follower",
    factor: 1.5,
    description: "Follower arrival speed +50%.",
  },
  {
    id: "circle3",
    name: "Patient Circles",
    category: "Automation",
    cost: d(14000),
    knowledge: 1600,
    requires: ["circle", "pentagram2"],
    kind: "speed",
    factor: 1.15,
    description: "All summoning speed +15%.",
  },
  {
    id: "circle4",
    name: "Bound Machinery",
    category: "Automation",
    cost: d(70000),
    knowledge: 6500,
    requires: "circle3",
    kind: "cost",
    factor: 0.9,
    description: "All summon costs \u221210%.",
  },
  {
    id: "circle5",
    name: "Perpetual Invocation",
    category: "Automation",
    cost: d(300000),
    knowledge: 24000,
    requires: ["circle4", "pentagram4"],
    kind: "speed",
    factor: 1.3,
    description: "All summoning speed +30%.",
  },
  {
    id: "pentagram3",
    name: "Ninefold Seal",
    category: "Pentagram",
    cost: d(12000),
    knowledge: 1000,
    requires: "pentagram2",
    kind: "speed",
    factor: 1.2,
    description: "Summoning speed +20%.",
  },
  {
    id: "pentagram4",
    name: "Labyrinth of Names",
    category: "Pentagram",
    cost: d(60000),
    knowledge: 5000,
    requires: "pentagram3",
    kind: "speed",
    factor: 1.2,
    description: "Summoning speed +20%.",
  },
  {
    id: "pentagram5",
    name: "Perfect Inscription",
    category: "Pentagram",
    cost: d(250000),
    knowledge: 20000,
    requires: "pentagram4",
    kind: "speed",
    factor: 1.25,
    description: "Summoning speed +25%.",
  },
  {
    id: "geometry3",
    name: "Angles of War",
    category: "Sacred Geometry",
    cost: d(16000),
    knowledge: 1400,
    requires: "geometry2",
    kind: "power",
    factor: 1.3,
    description: "All army power +30%.",
  },
  {
    id: "geometry4",
    name: "Imperial Seal",
    category: "Sacred Geometry",
    cost: d(90000),
    knowledge: 7000,
    requires: ["geometry3", "incense3"],
    kind: "power",
    factor: 1.4,
    description: "All army power +40%.",
  },
  {
    id: "geometry5",
    name: "Worldbreaking Theorem",
    category: "Sacred Geometry",
    cost: d(450000),
    knowledge: 30000,
    requires: "geometry4",
    kind: "power",
    factor: 1.6,
    description: "All army power +60%.",
  },
  {
    id: "candles3",
    name: "Soul-fed Flame",
    category: "Candles",
    cost: d(10000),
    knowledge: 900,
    requires: "candles2",
    kind: "essence",
    factor: 1.3,
    description: "Essence generation +30%.",
  },
  {
    id: "candles4",
    name: "Eternal Pyre",
    category: "Candles",
    cost: d(65000),
    knowledge: 4500,
    requires: "candles3",
    kind: "essence",
    factor: 1.35,
    description: "Essence generation +35%.",
  },
  {
    id: "candles5",
    name: "Light Beyond Death",
    category: "Candles",
    cost: d(260000),
    knowledge: 18000,
    requires: "candles4",
    kind: "essence",
    factor: 1.5,
    description: "Essence generation +50%.",
  },
  {
    id: "incense3",
    name: "Ash of True Names",
    category: "Incense",
    cost: d(18000),
    knowledge: 1800,
    requires: "incense2",
    kind: "demonPower",
    factor: 1.3,
    description: "Power of tier IV\u2013VI demons +30%.",
  },
  {
    id: "incense4",
    name: "Breath of the Abyss",
    category: "Incense",
    cost: d(100000),
    knowledge: 8000,
    requires: "incense3",
    kind: "demonPower",
    factor: 1.4,
    description: "Power of tier IV\u2013VI demons +40%.",
  },
  {
    id: "incense5",
    name: "The Last Offering",
    category: "Incense",
    cost: d(500000),
    knowledge: 35000,
    requires: ["incense4", "geometry4"],
    kind: "demonPower",
    factor: 1.6,
    description: "Power of tier IV\u2013VI demons +60%.",
  },
  {
    id: "study",
    name: "Marginal Notes",
    category: "Forbidden Study",
    cost: d(80),
    knowledge: 20,
    kind: "knowledge",
    factor: 1.2,
    description: "Knowledge generation +20%.",
  },
  {
    id: "study2",
    name: "Indexed Grimoire",
    category: "Forbidden Study",
    cost: d(800),
    knowledge: 180,
    requires: "study",
    kind: "knowledge",
    factor: 1.25,
    description: "Knowledge generation +25%.",
  },
  {
    id: "study3",
    name: "Scriptorium",
    category: "Forbidden Study",
    cost: d(8000),
    knowledge: 1200,
    requires: "study2",
    kind: "knowledge",
    factor: 1.3,
    description: "Knowledge generation +30%.",
  },
  {
    id: "study4",
    name: "Living Archive",
    category: "Forbidden Study",
    cost: d(50000),
    knowledge: 6000,
    requires: "study3",
    kind: "knowledge",
    factor: 1.4,
    description: "Knowledge generation +40%.",
  },
  {
    id: "study5",
    name: "Omniscient Manuscript",
    category: "Forbidden Study",
    cost: d(240000),
    knowledge: 25000,
    requires: "study4",
    kind: "knowledge",
    factor: 1.5,
    description: "Knowledge generation +50%.",
  },
  {
    id: "slavic_study",
    name: "Book of Veles",
    region: "slavic",
    category: "Forbidden Study",
    requires: "study5",
    cost: d(1500000),
    knowledge: 50000,
    kind: "knowledge",
    factor: 1.75,
    description: "Knowledge generation +75%.",
  },
  {
    id: "slavic_seal",
    name: "Knot of the Three Worlds",
    region: "slavic",
    category: "Pentagram",
    requires: "pentagram5",
    cost: d(2000000),
    knowledge: 60000,
    kind: "speed",
    factor: 1.3,
    description: "All summoning speed +30%.",
  },
  {
    id: "slavic_circle",
    name: "Circle of the Grove",
    region: "slavic",
    category: "Automation",
    requires: "circle5",
    cost: d(3500000),
    knowledge: 70000,
    kind: "cost",
    factor: 0.85,
    description: "All summon costs −15%.",
  },
  {
    id: "slavic_candles",
    name: "Midsummer Bonfire",
    region: "slavic",
    category: "Candles",
    requires: "candles5",
    cost: d(2000000),
    knowledge: 55000,
    kind: "essence",
    factor: 1.6,
    description: "Essence generation +60%.",
  },
  {
    id: "slavic_geometry",
    name: "Perun’s Thunder",
    region: "slavic",
    category: "Sacred Geometry",
    requires: "geometry5",
    cost: d(6000000),
    knowledge: 100000,
    kind: "power",
    factor: 1.5,
    description: "All army power +50%.",
  },
  {
    id: "slavic_incense",
    name: "Offering to the Old Gods",
    region: "slavic",
    category: "Incense",
    requires: "incense5",
    cost: d(9000000),
    knowledge: 140000,
    kind: "slavicPower",
    factor: 2,
    description: "Power of all six Slavic entities ×2.",
  },
  {
    id: "slavic_charm",
    name: "Ancestral Covenant",
    region: "slavic",
    category: "Follower Gain",
    requires: "charm5",
    cost: d(1200000),
    knowledge: 45000,
    kind: "follower",
    factor: 1.75,
    description: "Follower arrival speed +75%.",
  },
];
// A fictional campaign through cities of antiquity and the historic Silk Road.
export const cities: CityDefinition[] = [
  {
    region: "ancient",
    id: "babylon",
    name: "Babylon",
    epithet: "The gate of empires",
    description: "Beyond the black river, the great gates wait in silence.",
    strength: d(60000),
    reward: 10,
  },
  {
    region: "ancient",
    id: "nineveh",
    name: "Nineveh",
    epithet: "The buried library",
    description: "A thousand forbidden names sleep beneath these walls.",
    strength: d(180000),
    reward: 15,
  },
  {
    region: "ancient",
    id: "persepolis",
    name: "Persepolis",
    epithet: "The throne of ashes",
    description: "An empty throne still commands an army of shadows.",
    strength: d(500000),
    reward: 20,
  },
  {
    region: "ancient",
    id: "samarkand",
    name: "Samarkand",
    epithet: "The crossroads of the unseen",
    description: "Every road carries a rumor. Every caravan carries a curse.",
    strength: d(1500000),
    reward: 25,
  },
  {
    region: "ancient",
    id: "baghdad",
    name: "Baghdad",
    epithet: "The circle of wisdom",
    description:
      "The ink of forgotten scholars stains the river beneath the city.",
    strength: d(4000000),
    reward: 35,
  },
  {
    region: "ancient",
    id: "alexandria",
    name: "Alexandria",
    epithet: "The last light",
    description: "At the edge of the sea, one last beacon refuses the dark.",
    strength: d(12000000),
    reward: 50,
  },
  {
    id: "nitra",
    name: "Nitra",
    region: "slavic",
    strength: d(30000000),
    reward: 65,
    epithet: "The hill of embers",
    description:
      "Beyond Alexandria, the northern hills shelter an older faith.",
  },
  {
    id: "velehrad",
    name: "Velehrad",
    region: "slavic",
    strength: d(90000000),
    reward: 85,
    epithet: "The sacred crossroads",
    description: "Oaths and old gods meet beneath these silent ramparts.",
  },
  {
    id: "praha",
    name: "Praha",
    region: "slavic",
    strength: d(270000000),
    reward: 110,
    epithet: "The city of thresholds",
    description: "Every doorway opens onto a different night.",
  },
  {
    id: "krakow",
    name: "Kraków",
    region: "slavic",
    strength: d(800000000),
    reward: 140,
    epithet: "The shadow beneath the hill",
    description: "Something ancient stirs below the foundations.",
  },
  {
    id: "kyiv",
    name: "Kyiv",
    region: "slavic",
    strength: d(2400000000),
    reward: 180,
    epithet: "The river of forgotten names",
    description: "The river carries the whispers of an uncounted host.",
  },
  {
    id: "novgorod",
    name: "Novgorod",
    region: "slavic",
    strength: d(7200000000),
    reward: 230,
    epithet: "The last winter",
    description: "Beyond the frozen gates, the forest waits for its master.",
  },
];
export const firstCity = cities[0];
